# Credit Card Processor - Development Docker Compose Configuration
# 
# SECURITY NOTES:
# - This configuration loads environment variables from .env file
# - Ensure .env file contains proper security settings for your environment
# - Never commit .env files containing production secrets to version control
# - For production: use secure secret management and update all default values

services:
  # Backend service - FastAPI with hot reload
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: credit-card-backend-dev
    ports:
      - "8001:8001"
    volumes:
      # Mount source code for hot reload
      - ./backend/app:/app/app
      - ./backend/requirements.txt:/app/requirements.txt:ro
      # Mount test files for testing
      - ./backend/tests:/app/tests:ro
      - ./tests:/app/root_tests:ro
      # Persistent data storage
      - ./backend/data:/app/data
    env_file:
      - .env
    environment:
      # Environment settings - loaded from .env file
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - DATABASE_URL=sqlite:///./data/database.db
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - DEBUG=${DEBUG:-false}
      
      # Security environment variables (loaded from .env file)
      - ADMIN_USERS=${ADMIN_USERS}
      - SESSION_SECRET_KEY=${SESSION_SECRET_KEY:-dev-session-secret-change-in-production-must-be-32-chars-minimum}
      - SESSION_TIMEOUT_MINUTES=${SESSION_TIMEOUT_MINUTES:-480}
      - MAX_LOGIN_ATTEMPTS=${MAX_LOGIN_ATTEMPTS:-5}
      - LOGIN_LOCKOUT_MINUTES=${LOGIN_LOCKOUT_MINUTES:-15}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://frontend:3000,http://localhost:8001}
      - TRUSTED_HOSTS=${TRUSTED_HOSTS:-localhost,127.0.0.1,*.local}
      - ENABLE_SECURITY_HEADERS=${ENABLE_SECURITY_HEADERS:-true}
      - FORCE_HTTPS=${FORCE_HTTPS:-false}
      - HSTS_MAX_AGE=${HSTS_MAX_AGE:-31536000}
      - RATE_LIMIT_REQUESTS=${RATE_LIMIT_REQUESTS:-100}
      - RATE_LIMIT_PERIOD=${RATE_LIMIT_PERIOD:-60}
      # Line-level features
      - LINES_ENABLED=${LINES_ENABLED:-true}
      - LINE_MATCHING_ENABLED=${LINE_MATCHING_ENABLED:-true}
      - INCLUDE_RAW_EXCERPTS=${INCLUDE_RAW_EXCERPTS:-false}
      
      # Enhanced Debug Logging Configuration
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ENABLE_REQUEST_LOGGING=${ENABLE_REQUEST_LOGGING:-true}
      - ENABLE_DATABASE_LOGGING=${ENABLE_DATABASE_LOGGING:-false}
      - ENABLE_PERFORMANCE_LOGGING=${ENABLE_PERFORMANCE_LOGGING:-false}
      - LOG_FORMAT=${LOG_FORMAT:-text}
      - REQUEST_ID_HEADER=${REQUEST_ID_HEADER:-X-Request-ID}
      
      # Hot reload settings
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    networks:
      - credit-card-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Frontend service - Vue 3 + Vite with hot reload
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: credit-card-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reload
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json:ro
      - ./frontend/vite.config.js:/app/vite.config.js:ro
      - ./frontend/tailwind.config.js:/app/tailwind.config.js:ro
      - ./frontend/postcss.config.js:/app/postcss.config.js:ro
      - ./frontend/index.html:/app/index.html:ro
      # Exclude node_modules to prevent conflicts
      - /app/node_modules
    env_file:
      - .env
    environment:
      # Vite development settings
      - NODE_ENV=development
      - DOCKER_ENV=true
      - VITE_API_BASE_URL=http://localhost:8001
      - VITE_APP_TITLE=Credit Card Processor (Dev)
      - VITE_DEV_USER=${VITE_DEV_USER:-rcox}
      # Enable hot reload
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    networks:
      - credit-card-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  credit-card-network:
    driver: bridge
    name: credit-card-dev-network

# Development volumes for data persistence
volumes:
  backend_data:
    driver: local
    name: credit-card-backend-data-dev