version: '3.8'

services:
  backend:
    build: 
      context: ../../backend
      dockerfile: Dockerfile.prod
    container_name: credit-card-backend-prod
    ports:
      - "8001:8001"
    env_file:
      - ../../.env.production
    volumes:
      - ../../data:/app/data
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile.prod
      args:
        - VITE_API_BASE_URL=http://localhost:8001
        - VITE_APP_TITLE=Credit Card Processor
        - VITE_DEV_USER=rcox
    container_name: credit-card-frontend-prod
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:15-alpine
    container_name: credit-card-db-prod
    env_file:
      - ../../.env.production
    environment:
      POSTGRES_DB: creditcard
      POSTGRES_USER: creditcard_user
      POSTGRES_PASSWORD: cc_prod_secure_password_2024!
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../backups:/backups
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U creditcard_user -d creditcard"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local