apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
  namespace: credit-card-processor
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "${IDENTITY_CLIENT_ID}"
    keyvaultName: "iius-akv"
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - |
          objectName: azure-client-id
          objectType: secret
        - |
          objectName: azure-client-secret
          objectType: secret
        - |
          objectName: azure-tenant-id
          objectType: secret
        - |
          objectName: session-secret-key
          objectType: secret
        - |
          objectName: db-password
          objectType: secret
        - |
          objectName: database-connection-string
          objectType: secret
        - |
          objectName: doc-intelligence-api-key
          objectType: secret
        - |
          objectName: storage-account-key
          objectType: secret
    tenantId: "${TENANT_ID}"
  secretObjects:
  - secretName: app-secrets
    type: Opaque
    data:
    - objectName: azure-client-id
      key: AZURE_CLIENT_ID
    - objectName: azure-client-secret
      key: AZURE_CLIENT_SECRET
    - objectName: azure-tenant-id
      key: AZURE_TENANT_ID
    - objectName: session-secret-key
      key: SESSION_SECRET_KEY
    - objectName: db-password
      key: DB_PASSWORD
    - objectName: database-connection-string
      key: DATABASE_CONNECTION_STRING
    - objectName: doc-intelligence-api-key
      key: DOC_INTELLIGENCE_API_KEY
    - objectName: storage-account-key
      key: STORAGE_ACCOUNT_KEY


