apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: credit-card-processor
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            azure.workload.identity/use: "true"
        spec:
          serviceAccountName: backup-sa
          containers:
          - name: postgres-backup
            image: iiusacr.azurecr.io/backup:latest
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
            - name: DB_HOST
              value: postgres
            - name: DB_USER
              value: ccuser
            - name: DB_NAME
              value: creditcard
            - name: STORAGE_ACCOUNT
              value: cssa915121f46f2ae0d374e7
            - name: CONTAINER_NAME
              value: backups
            volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets"
              readOnly: true
          restartPolicy: OnFailure
          volumes:
          - name: secrets-store
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: azure-keyvault

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-sa
  namespace: credit-card-processor
  annotations:
    azure.workload.identity/client-id: "${IDENTITY_CLIENT_ID}"


