# Prometheus alert rules for Credit Card Processor
# These rules define conditions that trigger alerts

groups:
  - name: credit-card-processor.rules
    rules:
      # Application availability alerts
      - alert: ApplicationDown
        expr: up{job="credit-card-backend"} == 0
        for: 1m
        labels:
          severity: critical
          component: application
        annotations:
          summary: "Credit Card Processor application is down"
          description: "The Credit Card Processor backend has been down for more than 1 minute"
          runbook_url: "https://internal.example.com/runbooks/credit-card-processor-down"

      - alert: HighErrorRate
        expr: rate(http_requests_total{job="credit-card-backend",code=~"5.."}[5m]) / rate(http_requests_total{job="credit-card-backend"}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          component: application
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for the last 5 minutes"

      - alert: SlowResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="credit-card-backend"}[5m])) > 5
        for: 5m
        labels:
          severity: warning
          component: application
        annotations:
          summary: "Slow response time detected"
          description: "95th percentile response time is {{ $value }}s"

      # System resource alerts
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 0.9
        for: 2m
        labels:
          severity: warning
          component: system
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 90% (current: {{ $value | humanizePercentage }})"

      - alert: CriticalMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 0.95
        for: 1m
        labels:
          severity: critical
          component: system
        annotations:
          summary: "Critical memory usage"
          description: "Memory usage is above 95% (current: {{ $value | humanizePercentage }})"

      - alert: HighCpuUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          component: system
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is above 80% (current: {{ $value }}%)"

      - alert: CriticalCpuUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 95
        for: 2m
        labels:
          severity: critical
          component: system
        annotations:
          summary: "Critical CPU usage"
          description: "CPU usage is above 95% (current: {{ $value }}%)"

      # Disk space alerts
      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 20
        for: 1m
        labels:
          severity: warning
          component: system
        annotations:
          summary: "Low disk space"
          description: "Disk space is below 20% (current: {{ $value }}%)"

      - alert: CriticalDiskSpace
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 10
        for: 1m
        labels:
          severity: critical
          component: system
        annotations:
          summary: "Critical disk space"
          description: "Disk space is below 10% (current: {{ $value }}%)"

      # Database alerts
      - alert: DatabaseConnectionIssues
        expr: increase(database_connection_errors_total[5m]) > 5
        for: 2m
        labels:
          severity: warning
          component: database
        annotations:
          summary: "Database connection issues"
          description: "{{ $value }} database connection errors in the last 5 minutes"

      - alert: SlowDatabaseQueries
        expr: rate(database_query_duration_seconds_sum[5m]) / rate(database_query_duration_seconds_count[5m]) > 1
        for: 5m
        labels:
          severity: warning
          component: database
        annotations:
          summary: "Slow database queries"
          description: "Average query time is {{ $value }}s"

      # Security alerts
      - alert: HighFailedAuthAttempts
        expr: rate(auth_failures_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
          component: security
        annotations:
          summary: "High number of authentication failures"
          description: "{{ $value }} authentication failures per second"

      - alert: SuspiciousActivity
        expr: rate(security_events_total{type="suspicious"}[5m]) > 1
        for: 1m
        labels:
          severity: critical
          component: security
        annotations:
          summary: "Suspicious activity detected"
          description: "{{ $value }} suspicious security events per second"

      # nginx alerts
      - alert: NginxDown
        expr: up{job="nginx"} == 0
        for: 1m
        labels:
          severity: critical
          component: nginx
        annotations:
          summary: "nginx is down"
          description: "nginx has been down for more than 1 minute"

      - alert: HighNginxErrorRate
        expr: rate(nginx_http_requests_total{status=~"5.."}[5m]) / rate(nginx_http_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
          component: nginx
        annotations:
          summary: "High nginx error rate"
          description: "nginx error rate is {{ $value | humanizePercentage }}"

      # SSL certificate alerts
      - alert: SSLCertificateExpiringSoon
        expr: (ssl_certificate_expiry_timestamp - time()) / 86400 < 30
        for: 1h
        labels:
          severity: warning
          component: ssl
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate will expire in {{ $value }} days"

      - alert: SSLCertificateExpired
        expr: ssl_certificate_expiry_timestamp - time() < 0
        for: 1m
        labels:
          severity: critical
          component: ssl
        annotations:
          summary: "SSL certificate expired"
          description: "SSL certificate has expired"

      # Application-specific business logic alerts
      - alert: ProcessingQueueBacklog
        expr: processing_queue_size > 1000
        for: 5m
        labels:
          severity: warning
          component: processing
        annotations:
          summary: "Large processing queue backlog"
          description: "Processing queue has {{ $value }} items"

      - alert: FailedFileUploads
        expr: rate(file_upload_failures_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          component: upload
        annotations:
          summary: "High file upload failure rate"
          description: "{{ $value }} file upload failures per second"

  - name: credit-card-processor.recording
    rules:
      # Recording rules for commonly used expressions
      - record: instance:node_cpu_utilisation:rate5m
        expr: 1 - avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m]))

      - record: instance:node_memory_utilisation:ratio
        expr: 1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)

      - record: instance:node_filesystem_utilisation:ratio
        expr: 1 - (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"})

      - record: app:http_request_rate:rate5m
        expr: rate(http_requests_total{job="credit-card-backend"}[5m])

      - record: app:http_error_rate:rate5m
        expr: rate(http_requests_total{job="credit-card-backend",code=~"5.."}[5m])

      - record: app:http_request_duration:p95:rate5m
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="credit-card-backend"}[5m]))